### ISSUE TITLE
Error also when using Claude's models starting with the new update in the old one it still works

### ISSUE THREAD

**Issue by start-life** [Doriandarko/maestro#19]
Error also when using Claude's models starting with the new update in the old one it still works in the previous script it still works starting with the new update there are errors all the time

C:\zxcv\maestro-main\maestro-main>python maestro.py
Please enter your objective with or without a text file path: Make me a snake game, including scoring and record keeping, and a 3D graphical interface
Do you want to use search? (y/n): n

Calling Orchestrator for your objective
Input Tokens: 224, Output Tokens: 373
Opus Orchestrator Cost: $0.03
╭─ Opus Orchestrator ──────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Here is the next sub-task to achieve the objective of making a snake game with scoring, record keeping, and a 3D     │
│ graphical interface:                                                                                                 │
│                                                                                                                      │
│ Sub-task: Set up the basic game structure and 3D environment                                                         │
│ Create a new Python file and import the necessary libraries for 3D rendering (e.g. Pygame, OpenGL).                  │
│ Set up a basic game loop structure with initialization, main loop, and cleanup sections.                             │
│ Create a simple 3D environment using OpenGL primitives to represent the game board.                                  │
│ Implement camera controls to allow the player to view the game board from different angles.                          │
│ Add basic lighting to the scene to enhance the 3D effect.                                                            │
│                                                                                                                      │
│ Prompt for subagent:                                                                                                 │
│ Your task is to set up the foundation for a 3D snake game using Python and OpenGL. Create a new Python file and      │
│ import the required libraries for 3D rendering, such as Pygame and OpenGL. Set up a basic game loop structure with   │
│ sections for initialization, the main loop, and cleanup.                                                             │
│                                                                                                                      │
│ Use OpenGL primitives to create a simple 3D environment representing the game board. The game board should be a      │
│ flat, rectangular surface. Implement camera controls that allow the player to view the game board from different     │
│ angles using keyboard or mouse input.                                                                                │
│                                                                                                                      │
│ Add basic lighting to the scene to enhance the 3D effect and make the game board more visually appealing. Ensure     │
│ that the lighting is balanced and does not obstruct the player's view of the game board.                             │
│                                                                                                                      │
│ Test your code thoroughly to ensure that the game loop runs smoothly, the 3D environment is rendered correctly, and  │
│ the camera controls and lighting work as expected. If you encounter any issues or have suggestions for improvement,  │
│ please include them in your response.                                                                                │
╰────────────────────────────────────────────── Sending task to Haiku 👇 ──────────────────────────────────────────────╯
Traceback (most recent call last):
  File "C:\zxcv\maestro-main\maestro-main\maestro.py", line 234, in <module>
    sub_task_result = haiku_sub_agent(sub_task_prompt, search_query, haiku_tasks, use_search)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\zxcv\maestro-main\maestro-main\maestro.py", line 105, in haiku_sub_agent
    haiku_response = client.messages.create(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z5050\miniconda3\Lib\site-packages\anthropic\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z5050\miniconda3\Lib\site-packages\anthropic\resources\messages.py", line 678, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\z5050\miniconda3\Lib\site-packages\anthropic\_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\z5050\miniconda3\Lib\site-packages\anthropic\_base_client.py", line 897, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\z5050\miniconda3\Lib\site-packages\anthropic\_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages: text content blocks must be non-empty'}}

**Comment by jhundert** [comment]
I'm getting the exact same issue.

**Comment by jhundert** [comment]
The script works if I always answer:

Do you want to use search? (y/n): y

If I answer "n", the script produces the error above.

**Comment by Doriandarko** [comment]
ah ok will check, so it's only for the search variation right?

**Comment by Doriandarko** [comment]
Fixed!
