### ISSUE TITLE
Refactor the code

### ISSUE THREAD

**Issue by haseeb-heaven** [Doriandarko/maestro#5]
this is a good project, but you need to refactor the code and make different code files for different agents and different models for the opus and organize all the files in some directory.

Thanks

**Comment by 1aday** [comment]
it kinda inconvenient that the code gets saved with all the log in an md file instead of actual code files with the right extension, anyway to fix this?

**Comment by haseeb-heaven** [comment]
I dont know why people downvoted its good fair suggestion to refactor and organise the code.

**Comment by marckohlbrugge** [comment]
@haseeb-heaven I think the reason people downvoted your suggestion is because it’s easier to get a full understanding of the code with everything in one place.

The code is very simple and there are very few lines of code. Splitting it across multiple files introduces unneeded complexity.

**Comment by haseeb-heaven** [comment]
But if it grows larger over time then for modular codebase you need to organise it

**Comment by marckohlbrugge** [comment]
https://wiki.c2.com/?PrematureOptimization

**Comment by 1aday** [comment]
its just cleaner to have the out put files separated for example for an html5 app you have a directly with the right file structure ready.
